[general]
live_config_reload = true

[window]
opacity = 0.8
blur = true
dimensions = { columns = 182, lines = 42}

[font]
size = 15.0

[scrolling]
history = 100000

[keyboard]
bindings = [
	{ key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]
